const GET_LATEST_NEWS = "GET_LATEST_NEWS";
const GET_LATEST_NEWS_PENDING = "GET_LATEST_NEWS_PENDING";
const GET_LATEST_NEWS_FULFILLED = "GET_LATEST_NEWS_FULFILLED";
const GET_LATEST_NEWS_REJECTED = "GET_LATEST_NEWS_REJECTED";

export default {
  GET_LATEST_NEWS,
  GET_LATEST_NEWS_PENDING,
  GET_LATEST_NEWS_FULFILLED,
  GET_LATEST_NEWS_REJECTED,
};
